name: Publish to Maven & Create GitHub Release

on:
  push:
    branches:
      - version/**
  workflow_dispatch:

jobs:
  build:
    uses: SLNE-Development/surf-workflows/.github/workflows/build-publish-release-gradle.yml@master
    with:
      modules: "surf-trophy-paper-*-all.jar;surf-trophy-microservice-*-all.jar"
    secrets: inherit